83 frontend enhance picklist page
Yeti-Robotics/2022-scouting-real pull request #84
Opened 2024-02-09 23:16 UTC by qwertycloudhub

Added teleOp Data

2024-02-09 23:27 UTC, drew-beamer requested changes

2024-02-09 23:27 UTC, drew-beamer commented on components/PicklistTable/index.tsx
@qwertycloudhub could you add the endgame columns as well?

2024-02-09 23:27 UTC, drew-beamer commented on app/picklist/page.tsx
>  		<main className='mx-auto max-w-[540px]'>
Add a bit of margin to the top, maybe mt-16?

2024-02-10 01:21 UTC, qwertycloudhub commented on components/PicklistTable/index.tsx
Got it

2024-02-10 15:44 UTC, drew-beamer approved these changes
lgtm

2024-02-10 15:45 UTC, merged